using System.Collections.Concurrent;
using System.Runtime.InteropServices;
using Reframe.Interop;

namespace Reframe.Core;

/// <summary>The three outcomes of Apply: no change / changed / failed (a protected window we can't touch; the caller reports "no permission" accordingly).</summary>
public enum ApplyOutcome { NoChange, Changed, Failed }

/// <summary>
/// Who caused a window to move. <see cref="User"/> = the human dragging/resizing directly (those go
/// through the OS, not <see cref="WindowOps"/>, so they're never tagged here — User is only the safe
/// default for an unlabelled call). <see cref="Takeover"/> = the borderless engine (auto or manual quick-
/// borderless) positioned it. <see cref="PersistenceRestore"/> = the window-persistence engine restored it.
/// <para>The persistence capture path checks <see cref="WindowOps.WasRecentlyMutatedByEngine"/> so that the
/// <c>LOCATIONCHANGE</c> events generated by our own (non-User) writes are NOT mistaken for user moves and
/// captured — closing both the "self-feedback" loop and the "_takeover hasn't been recorded yet" race
/// (the suppression flag is set at write time, before <c>_takeover.TryAdd</c>).</para>
/// </summary>
public enum MutationSource { User, Takeover, PersistenceRestore }

/// <summary>Acts on windows: strip border, position, snapshot and restore. Only operates when there's an actual change.</summary>
public static class WindowOps
{
    private sealed record Snapshot(long Style, long ExStyle, NativeMethods.RECT Rect);

    /// <summary>The original state before any change, used to "restore on rule-disable / engine-exit".</summary>
    private static readonly ConcurrentDictionary<IntPtr, Snapshot> _originals = new();

    // ---- Engine-write suppression: tells the persistence capture path "we (not the user) just moved this" ----
    // A non-User write registers (hWnd → expiry); the async LOCATIONCHANGE that follows arrives within this
    // window and is ignored by the capturer. Short TTL so a genuine user move right after isn't suppressed for long.
    private const int SuppressionWindowMs = 1500;
    private static readonly ConcurrentDictionary<IntPtr, long> _recentEngineWrites = new();

    /// <summary>Record that a non-User source just moved this window, so the persistence capturer ignores the resulting LOCATIONCHANGE for a short window.</summary>
    private static void MarkEngineWrite(IntPtr hWnd)
        => _recentEngineWrites[hWnd] = DateTime.UtcNow.AddMilliseconds(SuppressionWindowMs).Ticks;

    /// <summary>
    /// Whether this window was moved by the engine (Takeover / PersistenceRestore) within the last
    /// <see cref="SuppressionWindowMs"/> ms. The persistence capture path calls this to drop self-induced
    /// LOCATIONCHANGE events. Expired entries are pruned on read.
    /// </summary>
    public static bool WasRecentlyMutatedByEngine(IntPtr hWnd)
    {
        if (_recentEngineWrites.TryGetValue(hWnd, out long expiresTicks))
        {
            if (DateTime.UtcNow.Ticks <= expiresTicks) return true;
            _recentEngineWrites.TryRemove(hWnd, out _);
        }
        return false;
    }

    /// <summary>
    /// Apply the target state. Returns three outcomes: <see cref="ApplyOutcome.Changed"/> made an actual change;
    /// <see cref="ApplyOutcome.NoChange"/> the target was already met, nothing to do;
    /// <see cref="ApplyOutcome.Failed"/> the style change was rejected (protected/UWP window) — the caller
    /// should not register a takeover and should report "no permission".
    /// </summary>
    public static ApplyOutcome Apply(IntPtr hWnd, in PlacementResolver.Target t,
        MutationSource source = MutationSource.User)
    {
        // Whether this call created the window's snapshot for the first time — on failure we roll it back,
        // so an untouchable window isn't left with a stale snapshot.
        bool snapshotCreatedHere = false;
        bool changed = false;

        if (t.MakeBorderless)
        {
            snapshotCreatedHere |= EnsureSnapshot(hWnd);
            switch (StripBorder(hWnd))
            {
                case ApplyOutcome.Failed:
                    if (snapshotCreatedHere) _originals.TryRemove(hWnd, out _);
                    return ApplyOutcome.Failed;
                case ApplyOutcome.Changed:
                    changed = true;
                    break;
            }
        }

        if (t.Rect is { } r)
        {
            NativeMethods.GetWindowRect(hWnd, out var cur);
            int cw = r.Right - r.Left, ch = r.Bottom - r.Top;
            // ±2px tolerance: under DPI rounding / frame jitter, being off by a pixel or two doesn't count as
            // "different", so we avoid a pointless SetWindowPos resend and a tug-of-war with the game.
            bool same = Near(cur.Left, r.Left) && Near(cur.Top, r.Top) &&
                        Near(cur.Right - cur.Left, cw) && Near(cur.Bottom - cur.Top, ch);
            if (!same)
            {
                snapshotCreatedHere |= EnsureSnapshot(hWnd);
                if (NativeMethods.IsIconic(hWnd))
                    NativeMethods.ShowWindow(hWnd, NativeMethods.SW_RESTORE);

                // Pure move/resize, no Z-order change (topmost is handled separately below).
                NativeMethods.SetWindowPos(hWnd, IntPtr.Zero, r.Left, r.Top, cw, ch,
                    NativeMethods.SWP_NOZORDER | NativeMethods.SWP_NOACTIVATE |
                    NativeMethods.SWP_NOOWNERZORDER | NativeMethods.SWP_FRAMECHANGED);
                changed = true;
            }
        }

        // Topmost: only when the profile requests topmost AND the window isn't already TOPMOST do we send one
        // Z-order-changing SetWindowPos (dropping SWP_NOZORDER, using HWND_TOPMOST as the anchor). A
        // non-topmost profile leaves Z-order alone: it neither forces NOTOPMOST nor changes a normal window's
        // existing level — clearing topmost happens only in Restore, per the snapshot.
        if (t.Topmost)
        {
            snapshotCreatedHere |= EnsureSnapshot(hWnd);
            if (!IsTopmost(hWnd))
            {
                NativeMethods.SetWindowPos(hWnd, NativeMethods.HWND_TOPMOST, 0, 0, 0, 0,
                    NativeMethods.SWP_NOMOVE | NativeMethods.SWP_NOSIZE |
                    NativeMethods.SWP_NOACTIVATE | NativeMethods.SWP_NOOWNERZORDER);
                changed = true;
            }
        }

        // A non-User write (engine takeover) registers suppression so the persistence capturer ignores the
        // LOCATIONCHANGE this move triggers. Set before the caller records _takeover, closing the lag race.
        if (changed && source != MutationSource.User) MarkEngineWrite(hWnd);

        return changed ? ApplyOutcome.Changed : ApplyOutcome.NoChange;
    }

    /// <summary>Pixel tolerance for position/size comparison (DPI rounding jitter).</summary>
    private const int PosTolerance = 2;
    private static bool Near(int a, int b) => Math.Abs(a - b) <= PosTolerance;

    private static bool IsTopmost(IntPtr hWnd)
        => ((long)NativeMethods.GetWindowLongPtr(hWnd, NativeMethods.GWL_EXSTYLE)
            & NativeMethods.WS_EX_TOPMOST) != 0;

    /// <summary>Restore a single window to how it looked before takeover. Returns false if the window has no snapshot or the style restore was rejected.</summary>
    public static bool Restore(IntPtr hWnd, MutationSource source = MutationSource.User)
    {
        if (!_originals.TryRemove(hWnd, out var s)) return false;

        // A non-User restore (engine un-takeover) is our own move: suppress the resulting LOCATIONCHANGE from capture.
        if (source != MutationSource.User) MarkEngineWrite(hWnd);

        bool ok = SetWindowLongPtrChecked(hWnd, NativeMethods.GWL_STYLE, (IntPtr)s.Style);
        ok &= SetWindowLongPtrChecked(hWnd, NativeMethods.GWL_EXSTYLE, (IntPtr)s.ExStyle);

        // Restore position (no Z-order change); WS_EX_TOPMOST can't go through SetWindowLongPtr, so it's
        // restored separately below via a Z-order anchor.
        NativeMethods.SetWindowPos(hWnd, IntPtr.Zero,
            s.Rect.Left, s.Rect.Top, s.Rect.Right - s.Rect.Left, s.Rect.Bottom - s.Rect.Top,
            NativeMethods.SWP_NOZORDER | NativeMethods.SWP_NOACTIVATE |
            NativeMethods.SWP_NOOWNERZORDER | NativeMethods.SWP_FRAMECHANGED);

        // Restore the topmost state per the snapshot: originally topmost → still TOPMOST, originally not →
        // clear to NOTOPMOST (this is exactly "only clear topmost on windows we previously made topmost" —
        // if the snapshot wasn't topmost, this step undoes the topmost we added).
        bool wasTopmost = (s.ExStyle & NativeMethods.WS_EX_TOPMOST) != 0;
        IntPtr anchor = wasTopmost ? NativeMethods.HWND_TOPMOST : NativeMethods.HWND_NOTOPMOST;
        NativeMethods.SetWindowPos(hWnd, anchor, 0, 0, 0, 0,
            NativeMethods.SWP_NOMOVE | NativeMethods.SWP_NOSIZE |
            NativeMethods.SWP_NOACTIVATE | NativeMethods.SWP_NOOWNERZORDER);
        return ok;
    }

    /// <summary>Restore every managed window (engine stop / app exit).</summary>
    public static void RestoreAll(MutationSource source = MutationSource.User)
    {
        foreach (var hWnd in _originals.Keys)
            Restore(hWnd, source);
    }

    /// <summary>
    /// Restore a window to a geometry remembered by the window-persistence engine (distinct from the
    /// borderless <see cref="Restore"/>, which reverts our own takeover). Tagged
    /// <see cref="MutationSource.PersistenceRestore"/> so the LOCATIONCHANGE it triggers is suppressed from
    /// re-capture. A maximized record is positioned inside the target monitor first, then re-maximized there;
    /// otherwise the window is un-minimized/-maximized as needed and moved to the exact rect. Finishes with a
    /// frame redraw to clear the "black canvas at the old size" some apps leave after a resolution change.
    /// </summary>
    public static void RestorePlacement(IntPtr hWnd, int left, int top, int right, int bottom, int showCmd)
    {
        if (!NativeMethods.IsWindow(hWnd)) return;
        int w = Math.Max(1, right - left), h = Math.Max(1, bottom - top);

        if (showCmd == NativeMethods.SW_SHOWMAXIMIZED)
        {
            // Move onto the target monitor (so the maximize lands there), then maximize.
            NativeMethods.SetWindowPos(hWnd, IntPtr.Zero, left, top, w, h,
                NativeMethods.SWP_NOZORDER | NativeMethods.SWP_NOACTIVATE | NativeMethods.SWP_NOOWNERZORDER);
            NativeMethods.ShowWindow(hWnd, NativeMethods.SW_SHOWMAXIMIZED);
        }
        else
        {
            // A currently minimized/maximized window must be restored to normal before a precise move.
            var wp = new NativeMethods.WINDOWPLACEMENT { length = Marshal.SizeOf<NativeMethods.WINDOWPLACEMENT>() };
            if (NativeMethods.GetWindowPlacement(hWnd, ref wp) &&
                (wp.showCmd == NativeMethods.SW_SHOWMINIMIZED || wp.showCmd == NativeMethods.SW_SHOWMAXIMIZED))
                NativeMethods.ShowWindow(hWnd, NativeMethods.SW_RESTORE);

            NativeMethods.SetWindowPos(hWnd, IntPtr.Zero, left, top, w, h,
                NativeMethods.SWP_NOZORDER | NativeMethods.SWP_NOACTIVATE |
                NativeMethods.SWP_NOOWNERZORDER | NativeMethods.SWP_FRAMECHANGED);
        }

        MarkEngineWrite(hWnd); // PersistenceRestore is a non-User write: suppress the resulting LOCATIONCHANGE
        NativeMethods.RedrawWindow(hWnd, IntPtr.Zero, IntPtr.Zero,
            NativeMethods.RDW_INVALIDATE | NativeMethods.RDW_ERASE | NativeMethods.RDW_FRAME |
            NativeMethods.RDW_UPDATENOW | NativeMethods.RDW_ALLCHILDREN);
    }

    public static bool IsTracked(IntPtr hWnd) => _originals.ContainsKey(hWnd);

    /// <summary>
    /// Drop original snapshots whose handle is dead (<paramref name="isAlive"/> returns false). Handles get
    /// reused by the system — if a destroyed window's snapshot isn't cleared, a new window grabbing the same
    /// HWND would have <see cref="EnsureSnapshot"/> skip creating a snapshot (GetOrAdd hits the stale value),
    /// causing restore to write back the previous window's style/position (stale-snapshot pollution).
    /// Driven centrally by <see cref="Watcher"/>'s dead-window cleanup (passing NativeMethods.IsWindow).
    /// </summary>
    public static void ForgetDead(Func<IntPtr, bool> isAlive)
    {
        foreach (var h in _originals.Keys)
            if (!isAlive(h))
                _originals.TryRemove(h, out _);

        // Prune suppression entries for dead handles too (handles get reused; a stale entry could wrongly
        // suppress a new window's first user move). Expired entries are also dropped here opportunistically.
        long nowTicks = DateTime.UtcNow.Ticks;
        foreach (var kv in _recentEngineWrites)
            if (!isAlive(kv.Key) || nowTicks > kv.Value)
                _recentEngineWrites.TryRemove(kv.Key, out _);
    }

    /// <summary>Create the snapshot (if absent). Returns true if this call created a new snapshot (for failure-rollback decisions).</summary>
    private static bool EnsureSnapshot(IntPtr hWnd)
    {
        bool created = false;
        _originals.GetOrAdd(hWnd, h =>
        {
            created = true;
            long style = (long)NativeMethods.GetWindowLongPtr(h, NativeMethods.GWL_STYLE);
            long ex = (long)NativeMethods.GetWindowLongPtr(h, NativeMethods.GWL_EXSTYLE);
            NativeMethods.GetWindowRect(h, out var rect);
            return new Snapshot(style, ex, rect);
        });
        return created;
    }

    private static ApplyOutcome StripBorder(IntPtr hWnd)
    {
        long style = (long)NativeMethods.GetWindowLongPtr(hWnd, NativeMethods.GWL_STYLE);
        long ex = (long)NativeMethods.GetWindowLongPtr(hWnd, NativeMethods.GWL_EXSTYLE);

        long newStyle = style & ~(NativeMethods.WS_CAPTION | NativeMethods.WS_THICKFRAME |
                                  NativeMethods.WS_BORDER | NativeMethods.WS_DLGFRAME);
        long newEx = ex & ~(NativeMethods.WS_EX_DLGMODALFRAME | NativeMethods.WS_EX_WINDOWEDGE |
                            NativeMethods.WS_EX_CLIENTEDGE | NativeMethods.WS_EX_STATICEDGE);

        if (newStyle == style && newEx == ex) return ApplyOutcome.NoChange;

        if (!SetWindowLongPtrChecked(hWnd, NativeMethods.GWL_STYLE, (IntPtr)newStyle) ||
            !SetWindowLongPtrChecked(hWnd, NativeMethods.GWL_EXSTYLE, (IntPtr)newEx))
            return ApplyOutcome.Failed;

        NativeMethods.SetWindowPos(hWnd, IntPtr.Zero, 0, 0, 0, 0,
            NativeMethods.SWP_NOZORDER | NativeMethods.SWP_NOACTIVATE |
            NativeMethods.SWP_NOSIZE | NativeMethods.SWP_NOMOVE | NativeMethods.SWP_FRAMECHANGED);
        return ApplyOutcome.Changed;
    }

    /// <summary>
    /// Wraps SetWindowLongPtr with the standard "a return of 0 isn't necessarily success" check: clear the
    /// thread's last-error before the call; a non-zero return is success; on a 0 return, inspect last-error —
    /// 0 means the previous value really was 0 (success), non-zero means rejected (failure).
    /// </summary>
    private static bool SetWindowLongPtrChecked(IntPtr hWnd, int nIndex, IntPtr value)
    {
        NativeMethods.SetLastError(0);
        IntPtr prev = NativeMethods.SetWindowLongPtr(hWnd, nIndex, value);
        if (prev != IntPtr.Zero) return true;
        return Marshal.GetLastWin32Error() == 0;
    }
}
